name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        type: string
      publish_crates:
        description: 'Publish to crates.io'
        required: false
        type: boolean
        default: false

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write
  discussions: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Determine Version
      id: version
      run: |
        if [ "${{ github.event_name }}" = "push" ]; then
          VERSION=${GITHUB_REF#refs/tags/v}
        else
          VERSION="${{ github.event.inputs.version }}"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    
    - name: Get previous tag
      id: previoustag
      run: |
        PREVIOUS_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
        echo "previous_tag=$PREVIOUS_TAG" >> $GITHUB_OUTPUT
    
    - name: Generate Release Notes
      id: release_notes
      run: |
        cat > release_notes.md << 'EOF'
        ## What's New
        
        EOF
        
        if [ -z "${{ steps.previoustag.outputs.previous_tag }}" ]; then
          echo "Initial release of AWS SSM Connect CLI!" >> release_notes.md
          echo "" >> release_notes.md
          echo "### Features" >> release_notes.md
          echo "- Connect to EC2 instances via SSM using instance Name tags" >> release_notes.md
          echo "- List available instances with their connection status" >> release_notes.md
          echo "- Automatic profile and region management" >> release_notes.md
          echo "- Interactive instance selection when multiple matches found" >> release_notes.md
        else
          # Get commits since last tag
          git log ${{ steps.previoustag.outputs.previous_tag }}..HEAD --pretty=format:"- %s" --reverse | grep -E "^- (feat|fix|perf|refactor):" | sed 's/^- feat://' | sed 's/^- fix://' | sed 's/^- perf://' | sed 's/^- refactor://' >> release_notes.md || echo "- Various improvements and bug fixes" >> release_notes.md
        fi
        
        echo "" >> release_notes.md
        echo "### Installation" >> release_notes.md
        echo "" >> release_notes.md
        echo "Download the appropriate binary for your platform below, make it executable, and move it to your PATH:" >> release_notes.md
        echo "" >> release_notes.md
        echo '```bash' >> release_notes.md
        echo "chmod +x aws-ssm-connect-*" >> release_notes.md
        echo "sudo mv aws-ssm-connect-* /usr/local/bin/aws-ssm-connect" >> release_notes.md
        echo '```' >> release_notes.md
        echo "" >> release_notes.md
        echo "### Usage" >> release_notes.md
        echo "" >> release_notes.md
        echo '```bash' >> release_notes.md
        echo "# Connect to an instance by name" >> release_notes.md
        echo "aws-ssm-connect my-instance" >> release_notes.md
        echo "" >> release_notes.md
        echo "# List available instances" >> release_notes.md
        echo "aws-ssm-connect --list" >> release_notes.md
        echo "" >> release_notes.md
        echo "# Use a specific AWS profile" >> release_notes.md
        echo "aws-ssm-connect my-instance --profile production" >> release_notes.md
        echo '```' >> release_notes.md
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.version.outputs.version }}
        name: AWS SSM Connect v${{ steps.version.outputs.version }}
        body_path: ./release_notes.md
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}

  build-and-upload:
    name: Build and Upload
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # macOS
          - os: macos-latest
            target: aarch64-apple-darwin
            binary_name: aws-ssm-connect
            asset_name: aws-ssm-connect-aarch64-apple-darwin
          - os: macos-latest
            target: x86_64-apple-darwin
            binary_name: aws-ssm-connect
            asset_name: aws-ssm-connect-x86_64-apple-darwin
          
          # Linux
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_name: aws-ssm-connect
            asset_name: aws-ssm-connect-x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            binary_name: aws-ssm-connect
            asset_name: aws-ssm-connect-x86_64-unknown-linux-musl
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            binary_name: aws-ssm-connect
            asset_name: aws-ssm-connect-aarch64-unknown-linux-gnu
            use_cross: true
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            binary_name: aws-ssm-connect
            asset_name: aws-ssm-connect-aarch64-unknown-linux-musl
            use_cross: true
          
          # Windows
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary_name: aws-ssm-connect.exe
            asset_name: aws-ssm-connect-x86_64-pc-windows-msvc.exe
          - os: windows-latest
            target: i686-pc-windows-msvc
            binary_name: aws-ssm-connect.exe
            asset_name: aws-ssm-connect-i686-pc-windows-msvc.exe
          
          # BSD variants (using cross)
          - os: ubuntu-latest
            target: x86_64-unknown-freebsd
            binary_name: aws-ssm-connect
            asset_name: aws-ssm-connect-x86_64-unknown-freebsd
            use_cross: true
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    
    - name: Install cross
      if: matrix.use_cross == true
      run: cargo install cross --git https://github.com/cross-rs/cross
    
    - name: Install musl-tools (Linux)
      if: matrix.target == 'x86_64-unknown-linux-musl'
      run: sudo apt-get update && sudo apt-get install -y musl-tools
    
    - name: Update version in Cargo.toml
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "macOS" ]]; then
          sed -i '' 's/^version = .*/version = "${{ needs.create-release.outputs.version }}"/' Cargo.toml
        else
          sed -i 's/^version = .*/version = "${{ needs.create-release.outputs.version }}"/' Cargo.toml
        fi
    
    - name: Build (with cross)
      if: matrix.use_cross == true
      run: cross build --release --target ${{ matrix.target }}
    
    - name: Build (with cargo)
      if: matrix.use_cross != true
      run: cargo build --release --target ${{ matrix.target }}
    
    - name: Strip binary (Linux/macOS)
      if: runner.os != 'Windows'
      run: |
        if command -v strip >/dev/null 2>&1; then
          strip target/${{ matrix.target }}/release/${{ matrix.binary_name }} || true
        fi
    
    - name: Prepare Binary
      shell: bash
      run: |
        cp target/${{ matrix.target }}/release/${{ matrix.binary_name }} ${{ matrix.asset_name }}
        if [[ "$RUNNER_OS" != "Windows" ]]; then
          chmod +x ${{ matrix.asset_name }}
        fi
    
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ needs.create-release.outputs.version }}
        files: ./${{ matrix.asset_name }}
        token: ${{ secrets.GITHUB_TOKEN }}

  publish-crates:
    name: Publish to crates.io
    needs: [create-release, build-and-upload]
    runs-on: ubuntu-latest
    if: github.event.inputs.publish_crates == 'true' || (github.event_name == 'push' && contains(github.ref, 'refs/tags/'))
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Update version in Cargo.toml
      run: |
        sed -i 's/^version = .*/version = "${{ needs.create-release.outputs.version }}"/' Cargo.toml
    
    - name: Login to crates.io
      run: cargo login ${{ secrets.CRATES_IO_TOKEN }}
    
    - name: Publish to crates.io
      run: cargo publish --allow-dirty